### ISSUE TITLE
Chapter 10: current_cert must not be freed in verify_callback()

### ISSUE THREAD

**Issue by franzhollerer** [PacktPublishing/Demystifying-Cryptography-with-OpenSSL-3#3]
The verify_callback() function in Chapter 10, e.g. on page 198 through 200, contains the following code:

verify_callback():
```c
int verify_callback(int preverify_ok, X509_STORE_CTX* x509_store_ctx) {
    :
    X509* current_cert = X509_STORE_CTX_get_current_cert(x509_store_ctx);
    :
    :
    BIO_free(mem_bio);
    X509_free(current_cert);

    return preverify_ok;
}
```

But X509_STORE_CTX_get_current_cert() only returns a pointer to an internal structure:

```c
X509 *X509_STORE_CTX_get_current_cert(const X509_STORE_CTX *ctx)
{
    return ctx->current_cert;
}
```

Being said, it does not transfer ownership. Therefore, I think the call to X509_free() is a bug. It should be removed.

**Comment by alexeikh** [comment]
Thank you for the report.

I have added an Errata entry about the unneeded (and harmful) "X509_free()" code line on the Page 200 of the Book: commit 45d1c5d.
